ThaBinaryBeasts/GraceShopper

.eslintrc.json
=> Changes at eslint

.travis.yml, package-lock.json, package.json
=> started to implement travis-ci

server/api/items.js
Added basic express routing for items.
-Get all items
- Get a specific item by id.
=> Item routes

server/api/index.js, server/api/users.js, server/api/users.spec.js, server/db/models/user.spec.js
---
fixed items route.
Had to change the name from "item" to "items" in /server/api/index.js
=> fixed items route in server/api/index.js

client/store/index.js, client/store/item.js
---
item reducer created for get all and by id
=> created item reducer

client/components/AllItems.js, client/components/Item.js, client/components/SingleItem.js, client/routes.js, client/store/item.js
Working All Items component and Single (Selected) Item
---
=> completed AllItems and SingleItem

client/components/Home.js, client/components/navbar.js, client/routes.js, public/style.css
=> navBar and Home component

server/api/index.js, server/api/orders.js, server/db/models/index.js
=> Final working add to cart routes

server/api/index.js, server/api/orders.js, server/db/models/index.js
=> fixed routes to add to cart

server/api/orders.js
=> last cart routes with added item return

client/app.js, client/components/navbar.js, client/store/item.js, public/style.css, script/seed.js
=> Thunk for User Cart by Alex

client/components/navbar.js, client/store/index.js, client/store/item.js, client/store/order.js, public/style.css, server/api/orders.js, server/db/models/item.js, server/db/models/itemOrders.js, server/db/models/order.js
fixed routes for Add Cart and Get Cart, AddCard doest work at postman, but works fine when running the same route at the browser
---
=> Fixed cart routes with models

client/components/Cart.js, client/components/navbar.js, client/routes.js, client/store/order.js, server/api/orders.js
working get Cart thunk. Note: 
DO:
---
=> working get Cart thunk

client/components/Cart.js, server/api/orders.js
working cart render, still need delete and update
---
=> working cart render, still need delete and update

client/components/SingleItem.js
Alex and Josh added the 'Add To Cart' button functionality on the SingleItem react component. Also added the functionality to select a quantity of bottles to buy, with up/down buttons to change quantity.
---
=> Added the Add To Cart button functionality, and quantity per item

client/components/SingleItem.js, client/components/navbar.js, client/store/order.js, public/style.css, server/api/orders.js, server/db/models/order.js
ALL cart routes work;
Cart THUNKS are written, but not tested yet since we don't have an update/delete Cart elements written
---
=> fixed All Cart Routes And Thunks

client/components/AllItems.js, client/components/Cart.js, client/components/Item.js, client/components/SingleItem.js, client/components/navbar.js, client/store/order.js, public/style.css, server/api/orders.js, server/db/models/order.js
* [x ] merge guest's and user's carts.
---
=> After merge

client/components/Cart.js, client/components/Item.js, script/seed.js
=> User cart done

client/components/Cart.js, client/components/Home.js, client/components/Item.js, client/components/SingleItem.js, client/components/navbar.js, public/style.css, script/seed.js
=> some css with updated functionality

client/components/Cart.js, client/components/Checkout.js, client/components/auth-form.js, client/routes.js, client/store/order.js, server/api/orders.js, server/db/models/order.js
=> compleated CheckOut

client/components/Cart.js, client/components/SingleItem.js, server/db/models/user.js
=> Local storage cart

client/components/Cart.js, client/components/MyOrders.js, client/components/navbar.js, client/routes.js, client/store/item.js, client/store/order.js
=> completed working History

client/components/Cart.js, server/api/users.js
=> user routes are secured

client/components/Cart.js, client/components/SingleItem.js, client/components/auth-form.js, client/components/navbar.js, public/style.css
=> Buttonfixed

client/components/auth-form.js
=> fixed problem with logIn
